export const colors = {
    background: '#c9f0ff',
    backgroundSecondary: '#F8FCFF',
    backgroundGray: '#EEF6F6',
    backgroundCard: '#F8FCFF',
    backgroundCardHover: '#f0f9ff',
    backgroundGreen: '#EDFFF6',
    green: '#009C4A',
    greenHover: '#00ba58',
    backgroundRed: '#FFEDED',
    redLabel: '#E30013',
    redHover: '#f50014',
    backgroundHover: 'aliceblue',
    text: '#222222',
    textLight: '#FFFFFF',
    textGray: '#787878',
    blue: '#0A6AFF',
    textBlue: '#0A6AFF',
    input: '#d9e8ff',
    button: '#0A6AFF',
    buttonDisabled: '#8fbbff',
    buttonHover: '#0063fc',
    iconBlue: '#0A6AFF',
    red: '#ff2424',
}